### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
So, the previous icon doesn't really do a good job of telling the user what the app does. Also, it doesn't comply by [eOS HIG](https://elementary.io/docs/human-interface-guidelines#composition) regarding pictogram. So, I've modified the previous one to fix this.

### CODE REVIEW

**Comment by mohelm97** [comment]
Heey Thanks a lot @Fatih20 ,
This is very nice actually, what do you think about making "REC" and the circle white?

**Comment by Fatih20** [comment]
I can do that, but I don't think making the cirlce also look white like the "REC" will look good. I can make it a different gradient of red though.

**Comment by peteruithoven** [comment]
I personally don't think this is an improvement.

- It's generally a bad idea to use texts in icons. Mostly because it's hard to read in small versions. It's also not translatable
- There are a lot of elements in this logo (see: https://elementary.io/docs/human-interface-guidelines#dos-donts).
- I don't know if the physical screen is the right metaphor to use (see: https://elementary.io/docs/human-interface-guidelines#metaphors).
- The smaller versions don't properly simplify, giving more noise. Looks like they are simply resized? I'd recommend only putting your efforts in one size for now, to limit your work, one version will still allow you to share your ideas. 

> it doesn't comply by eOS HIG regarding pictogram

Would be good to include in what way next time.

**Comment by Fatih20** [comment]
I'll be "pixel fitting" the smaller versions immediately. I myself do think that you're right, there's a lot of icon going on and I'll rethink this as well. The pictogram violation is regarding the use of extruded (with the instructions clearly defined by the HIG) or inset (by somehow making it seems like the pictogram sunk to the base shape. What the previous icon did was extruded but not with the way the HIG clearly instructs. Because there are already a lot of icons that uses extruded, I think it's better to use inset. And because the metaphor of a recorder "sunk" to the screen.

**Comment by Fatih20** [comment]
Also the circle with rec is a metaphors for a very common user interface on camera that look like this:
https://www.colourbox.com/vector/camera-viewfinder-user-interface-vector-17866469

**Comment by Fatih20** [comment]
What do you think of this concept? The pixel fitting will be a pain so I would like to know your thought first.

**Comment by NathanBnm** [comment]
I agree with @peteruithoven 
Here I prefer the original version of the icon, it's simpler and more clear I think.

**Pull request closed without merging**
